language: rust
sudo: required
dist: trusty
rust:
    - stable
    - beta
    - nightly
cache: cargo
services: postgresql
before_script:
    - psql -c 'create_database serde_postgres;' -U postgres
matrix:
    allow_failures:
        - rust: nightly
